### ISSUE TITLE
physics/arcade/static group

### ISSUE THREAD

**Issue by tcbhardwaj** [photonstorm/phaser3-examples#108]
sprite is not colliding with static group

**Comment by dazigemm** [comment]
Hi,

I managed to get the sprite to collide with the group by changing line 50 to `this.physics.world.collide(sprite, group.getChildren());`

**Comment by samme** [comment]
Working correctly in v3.4.1-beta: <http://labs.phaser.io/edit.html?src=src\physics\arcade\static%20group.js>
