### ISSUE TITLE
Action examples - Grid Align does not work

### ISSUE THREAD

**Issue by luquitared** [photonstorm/phaser3-examples#109]
Under Action examples on the phaser 3 documentation the Grid Align does not work. After downloading the source code I was able to get the example to work but installing the dat JS library and loading a spritesheet for diamonds.

**Comment by dazigemm** [comment]
Hi luquitared,

Is this the Grid Align example you are talking about? 
https://labs.phaser.io/view.html?src=src\actions\grid%20align.js

**Comment by patloonytoon** [comment]
The above-linked example works for me fine. No errors.

**Comment by luquitared** [comment]
Well it is working now. Thank you
