### ISSUE TITLE
game objects/image/getBounds

### ISSUE THREAD

**Issue by raaaahman** [photonstorm/phaser3-examples#119]
Seems to be an example of rotating an image instead of the getBounds function.

**Comment by mzguimaraes** [comment]
I'm not sure which example you're referring to.  There is no image subdirectory under components, as you can see [here](https://labs.phaser.io/index.html?dir=components/).

**Comment by raaaahman** [comment]
I'm sorry, it was "game objects/images/getBounds" that I was writing about.

**Comment by mzguimaraes** [comment]
Yeah, that seems like it just copied the code from game objects/images/image rotation.  I'm submitting an updated example.

**Comment by photonstorm** [comment]
Thank you for reporting a problem with this example. It has now been fixed. You can find the updated version in this repo and on the labs.phaser.io site.
