### ISSUE TITLE
Example issue: Pause and resume doesn't resume

### ISSUE THREAD

**Issue by DannyT** [photonstorm/phaser3-examples#137]
Seems like the isFollowing() method isn't returning false when a follower is paused...

http://labs.phaser.io/view.html?src=src\paths\followers\pause%20and%20resume.js

**Comment by stonerich** [comment]
It seems the problem is that the pause and resume functions does not exist, instead the function names seems to be pauseFollow and resumeFollow.
Changing them makes the example work.

        this.input.on('pointerdown', function () {

            if (lemming.isFollowing())
            {
                lemming.pauseFollow();
            }
            else
            {
                lemming.resumeFollow();
            }

        });

**Comment by mzguimaraes** [comment]
I'll go ahead and put those changes in a PR.

**Comment by stonerich** [comment]
Thanks @mzguimaraes. I'm not really into the GitHub workflow as of now so I'm staying on the issue writing side for a while :)
