### ISSUE TITLE
Gif to animation example broken from 3.7.1

### ISSUE THREAD

**Issue by DannyT** [photonstorm/phaser3-examples#191]
http://labs.phaser.io/view.html?src=src\animation\gif%20to%20animation.js&v=3.10.1

3.7.1 seemingly included a bit of an overhaul of the multiatlas loader. The 3.6 version appears to have some behaviour that allows a number to be passed as an arg `this.load.multiatlas('sao', 1);` but that isn't valid in the latest version. What that was doing and should now be doing is a bit beyond me though I'm afraid.

**Comment by photonstorm** [comment]
Yeah it needed a new atlas format. I fixed this one last week.
