### ISSUE TITLE
Phaser.Event is not a constructor

### ISSUE THREAD

**Issue by pagesrichie** [photonstorm/phaser3-examples#20]
https://labs.phaser.io/view.html?src=src\events\078%20event%20dispatcher.js

Phaser.Event is not a constructor

**Comment by pagesrichie** [comment]
Actually, as of 03/07/2018 it appears none of the events example work in the events folder, not just the one I linked above.

https://labs.phaser.io/index.html?dir=events/

**Comment by photonstorm** [comment]
These have all been fixed.
