### ISSUE TITLE
Can't .destroy() game objects created 

### ISSUE THREAD

**Issue by Ravonus** [photonstorm/phaser3-examples#201]
var sprites = camera.createRect(6, 64, 'block');

Sprites created this way. I can update some aspects, but not others. Most importantly I can't seem to do a .destroy();

Easy way to test this is to just add .destroy into the forloop. None of the sprites should show, but they all still do. I have tried to do sprite[i].gameObject.destroy() resulting in a crash. sprite[i].destroy() appears to work, but nothing actually happens.

**Comment by photonstorm** [comment]
What is `camera.createRect` ? It's certainly not part of Phaser. Either way, this sounds like a support issue and not a problem with an example, so I'd suggest moving it to the forum or Slack / Discord.
