### ISSUE TITLE
Emitter not working when following sprite (able to reproduce in example) 

### ISSUE THREAD

**Issue by GregDevProjects** [photonstorm/phaser3-examples#205]
- Able to reproduce in this example: https://labs.phaser.io/view.html?src=src\game%20objects\particle%20emitter\follow%20sprite.js&v=3.11.0

- The example works again when I set the version to 3.10.1

**Comment by photonstorm** [comment]
Related: https://github.com/photonstorm/phaser/issues/3851 (and now fixed in master)
