### ISSUE TITLE
Particle Editor Texture example not working in 3.11

### ISSUE THREAD

**Issue by RetroVX** [photonstorm/phaser3-examples#210]
https://labs.phaser.io/view.html?src=src/game%20objects/particle%20emitter/emit%20from%20texture.js&v=3.11.0

The example works in 3.10 and in dev build but not 3.11. This is causing an issue with particle emitters not showing the particles(in an atlus or individual sprites) in my project.

Working with the current dev build 3.12 beta 1 to fix this at the moment.

**Comment by aleskozina** [comment]
Hi there!

Same goes for this [example](http://labs.phaser.io/view.html?src=src\game%20objects\particle%20emitter\particles%20on%20a%20moving%20curve.js&v=3.11.0) - v3.11.0. Tested down till 3.6.x

I could fix the data-set error by just using the `setData`-method on the GameObject. After this there is some problem with the `setDraggable` which i, unfortunately, i could not solve :-) (im a fresh phaser3 user)

Kr
Ales

**Comment by photonstorm** [comment]
Going to close this because it's already fixed in 3.12. If you need it to work in 3.11, remove the blend mode from your particles and they'll render correctly.
