### ISSUE TITLE
pointerover don't work on smartphone (touch)

### ISSUE THREAD

**Issue by simaagaard** [photonstorm/phaser3-examples#220]
Like in this example:
http://labs.phaser.io/view.html?src=src\input\mouse\circle%20hit%20area.js

**Comment by photonstorm** [comment]
This is a mouse specific example. Even so, neither pointerover nor pointerout work on touch (the code for it literally isn't in the API, so this isn't an issue with the example itself)

**Comment by simaagaard** [comment]
Hey Richard

Are you planning on making pointerover work on touch?


Med Venlig Hilsen

Simon Aagaard

sim@aagaard.dk

(+45) 5219 1688

8200 Aarhus N


________________________________
Fra: Richard Davey <notifications@github.com>
Sendt: 9. august 2018 00:04
Til: photonstorm/phaser3-examples
Cc: Simon Aagaard; Author
Emne: Re: [photonstorm/phaser3-examples] pointerover don't work on smartphone (touch) (#220)


This is a mouse specific example. Even so, neither pointerover nor pointerout work on touch (the code for it literally isn't in the API, so this isn't an issue with the example itself)
