### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by flockonus** [photonstorm/phaser3-examples#226]
Hello!

I noticed the project got a package.json file, but i couldn't pull it from npm, is it published?

On the other hand I could download the latest from github like this:
`npm install git://github.com:photonstorm/phaser3-examples.git#862a13373be4175e4e96dac49f3eed89bde635c4 --save  --ignore-scripts`

Notice the --ignore-scripts was necessary as some postinstall script is erroring, but I just needed the assets to try out examples on my own.

Thanks!

**Comment by photonstorm** [comment]
The repo is too large for npm.

**Comment by flockonus** [comment]
makes sense :D 
As suggestion, for other ppl installing from the GH repo, if the postinstall scripts are not required it would be nice to remove the server init as it seems to rely on some global binary installed

**Comment by hexus** [comment]
You can also simply `npm install photonstorm/phaser-3-examples`  instead of using the full repo URL.

**Comment by flockonus** [comment]
Good point hexus. Just for my project I wanted to be sure certain assets would be there for sure, which is why i've ref. the hash

**Comment by hexus** [comment]
> Good point hexus. Just for my project I wanted to be sure certain assets would be there for sure, which is why i've ref. the hash

Fair enough. That's what package-lock.json is for though. :slightly_smiling_face:
