### ISSUE TITLE
Minimap camera has incorrect size/position 

### ISSUE THREAD

**Issue by GregDevProjects** [photonstorm/phaser3-examples#231]
Noticing some strange behavior with the minimap camera when I switch back and forth between 3.11 and 3.12 

http://labs.phaser.io/view.html?src=src/camera\minimap%20camera.js

- the positioning/size of the minimap isn't respected 
- camera background appearing outside of the minimap

**Comment by photonstorm** [comment]
Yup, this is already fixed in the 3.13 release (swap to 'dev' and it should be fine again)
