### ISSUE TITLE
animation / texture atlas animation example broken from 3.11.0

### ISSUE THREAD

**Issue by petermmiller** [photonstorm/phaser3-examples#234]
Example looks fine <= 3.10.1; >= 3.11.0 inc Dev Build shows glitches around the sea-creatures (except the crabs at the bottom).
Running it in an IFrame rather than a div seems to show it broken for any version >= 3.0.0 inc Dev Build.

Chrome:  Version 69.0.3497.81 (Official Build) (64-bit)

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.

**Comment by petermmiller** [comment]
Tested fixed in Dev Build for both div and IFrame.  Thanks heaps!!!
