### ISSUE TITLE
Collision is not occuring for balls falling on tiles

### ISSUE THREAD

**Issue by blachawk** [photonstorm/phaser3-examples#235]
Within the following 2 examples...

[source 1](http://labs.phaser.io/edit.html?src=src/game%20objects\tilemap\static\set%20colliding%20by%20collision%20data.js)
[source 2](http://labs.phaser.io/view.html?src=src/game%20objects\tilemap\static\set%20colliding%20by%20collision%20data.js&v=dev)

...The colorful balls are failing to bounce on the grey surfaces. They just keep falling until off screen.  Tested on my windows 10 desktop on Chrome, as well as on my Samsung galaxy S9 device.

**Comment by photonstorm** [comment]
Yes, this was a test of the new Tiled 1.2 loader which failed, but is working fine now. Example running properly with 3.14 Beta 1.
