### ISSUE TITLE
Example animation broken for version 3.11 and newer

### ISSUE THREAD

**Issue by sergeod9** [photonstorm/phaser3-examples#239]
http://labs.phaser.io/view.html?src=src%5Canimation%5Ctexture%20atlas%20animation.js&v=3.10.1

Device and OS: Ipad pro, ios 12
Browser: Chrome 

Animation broken for versions 3.11, 3.12, 3.13, older version have no issues.

**Comment by photonstorm** [comment]
Thank you for submitting this issue. We have fixed this and the fix has been pushed to the `master` branch. It will be part of the next release. If you get time to build and test it for yourself we would appreciate that.
