### ISSUE TITLE
TypeError with Phaser 3.14.0

### ISSUE THREAD

**Issue by blachawk** [photonstorm/phaser3-examples#243]
[This example](https://labs.phaser.io/edit.html?src=src/input\mouse\multi%20camera%20hit%20test.js) displays the following error

> Uncaught TypeError: camera.getWorldPoint is not a function

**Comment by photonstorm** [comment]
This example needs removing, it hasn't been a function since 3.11.

**Comment by photonstorm** [comment]
There, nuked.

**Comment by blachawk** [comment]
Understood, but its one of the only examples in the labs that uses "setHitArea" as a visual straining example, unless we should not focus on this property due to there being an alternative way...

**Comment by photonstorm** [comment]
There's no reason to ever need to use `setHitArea` directly that I can think of.
