### ISSUE TITLE
Chunky Raster Bars lost color on canvas since Phaser 3.12

### ISSUE THREAD

**Issue by Darky-Lucera** [photonstorm/phaser3-examples#250]
Here you can see the colored bars:
https://labs.phaser.io/view.html?force=Canvas&v=3.11.0&src=src\demoscene\chunky%20raster%20bars.js

Here you cannot see the colors (only black & white):
https://labs.phaser.io/view.html?force=Canvas&v=3.12.0&src=src\demoscene\chunky%20raster%20bars.js

In WebGL it works fine.

**Comment by photonstorm** [comment]
The effect requires WebGL because it uses tinting (so when forced to canvas, like those links above, it won't work properly). The reason 3.11 appears to work is that it doesn't support forcing canvas mode, so it's actually still running in WebGL.
