### ISSUE TITLE
Many examples on labs.phaser.io are out of date with this repo

### ISSUE THREAD

**Issue by Matthew-Herman** [photonstorm/phaser3-examples#68]
After looking at many of the issues @tgrajewski opened with broken examples on labs.phaser.io, I realized that many examples on that site are out of date with this repo, and that simply updating the site would fix a lot of these broken examples.

**Comment by photonstorm** [comment]
The site and this repo are the same thing. Every push made to this repo is automatically synced to the site, so they are exact mirrors. What needs to happen is people keep reporting broken ones (thank you to those who have so far) and, when time allows, we’ll either fix or remove them.

**Comment by Matthew-Herman** [comment]
Sorry I should have given more detail in my comment. In #39 we see that <http://labs.phaser.io/view.html?src=src\geom\ellipse\circumference%20point.js> is a broken example online. But in this repository the equivalent example is <https://github.com/photonstorm/phaser3-examples/blob/master/public/src/geom/ellipse/circumference.js> and they don't match.

The example online is broken but the current one in the repository works.

This seemed to be the case for many of the broken examples recently reported.
