### ISSUE TITLE
Input / Gamepad / Move Sprite

### ISSUE THREAD

**Issue by tgrajewski** [photonstorm/phaser3-examples#71]
https://labs.phaser.io/view.html?src=src\input\gamepad\move%20sprite.js

No gamepad detected here. Various browsers, Xbox 360 gamepad on Windows.

**Comment by eyseman** [comment]
Similar issue here. When I do try to access the gamepad object in my project, I do get a GamepadManager, yet no pads are detected.  Xbox 360 gamepad on Mac OS, consistent behaviour over various browsers
