### ISSUE TITLE
Initial install opens wrong URL

### ISSUE THREAD

**Issue by stahlmanDesign** [photonstorm/phaser3-examples#92]
after `npm install` or `npm start` the script opens `http://localhost//127.0.0.1:8080`

It should either open `http://127.0.0.1:8080` or `http://localhost:8080` but not a combination of both.

Navigating to one or the other works correctly

**Comment by stahlmanDesign** [comment]
I noticed the issue on MacOS 10.12

**Comment by photonstorm** [comment]
Doesn't happen for me either. `npm start` issues the command `./node_modules/.bin/http-server -s -o`. The `-o` is 'open browser' and the `-s` is 'do it quietly'. We don't actually specify the URL or port to open, it just uses the defaults. Are you sure your browser isn't doing some weird redirection?

**Comment by stahlmanDesign** [comment]
Hmm, looks like it's Safari. In Mac OS settings > General I switched default browser to Chrome and now `npm start` behaves as expected. Firefox is also OK. Even Opera is OK.

It's not really a big deal because I understand how to find the right path, I just thought others might have this problem, but it seems only those with Safari as the default browser. I don't think it's an issue with the repo so closing.
