### ISSUE TITLE
Sex Comments in Source Documentation

### ISSUE THREAD

**Issue by robmuh** [photonstorm/phaser3-examples#93]
While I completely laughed and enjoyed the comment referring to good docs being like sex (based on its empirical accuracy), I am forced to suggest that it be removed since I now have 9-year-olds putting it into their games and many of their conservative Southern parents would definitely not approve (We are talking about people who hate video games in general and who have complained about Minecraft being too violent. I kid you not). I would just hate for a parent to run across one and suddenly demonize Phaser and the community over it. Your choice, of course. Just informing you.

https://github.com/photonstorm/phaser/blob/2cd7da01261729e01ef002a9a6a10a4c9f19351a/src/phaser.js#L59

**Comment by photonstorm** [comment]
It shouldn't appear in any games as long as you use a minified build of Phaser, as all comments are removed during the minification process. Even so, I'll take this into consideration.

**Comment by robmuh** [comment]
Yes, of course. The reason I mention it is because I specifically chose the non-minified version to encourage reading the actual source by my students both out of appreciation for the Herculean effort as well as to get a sense of what such a project requires. Since the comment is near the end every single person who has opened it has seen it. Honestly, I get that this is not a big thing and understand if you close this issue. But when I have a young person show their mom or dad how awesome and ominous the phaser.js code is (which is not unlikely because they do think it is so cool) it is probable that non-technical, conservative, parents will read it (including people like the former CIO of BOA and CTO of PayPal, both of whom are parents).

**Comment by photonstorm** [comment]
I've updated it.
